spring.application.name=biddingengine

# PostgreSQL Configuration (from Neon)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Redis Configuration (from Upstash)
spring.data.redis.url=${REDIS_URL}

# Server Configuration
server.port=${PORT:8080}

