spring.application.name=biddingengine

# PostgreSQL Configuration (from Neon)
spring.datasource.username=${NEON_DATABASE_USERNAME}
spring.datasource.password=${NEON_DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url = jdbc:postgresql://ep-polished-shadow-am6hvn6c-pooler.c-5.us-east-1.aws.neon.tech/biddinengine_db?sslmode=require&channel_binding=require

# Redis Configuration (from Upstash)
spring.data.redis.url=${REDIS_URL}

# Server Configuration
server.port=${PORT:8080}

