spring.application.name=biddingengine

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Server Configuration
server.port=${PORT:8080}

